### ISSUE TITLE
Relicensing to LGPLv2

### ISSUE THREAD

**Issue by samth** [racket/math#10]
While almost all of Racket has been distributed with version 2 of the LGPL, the math library contained an explicit reference to LGPL v3 for the last several years. We would like to change back to version 2, which we've already done going forward with 47b6122fe797.

The significant contributions by people we haven't contacted yet are by @eu90h and @endobson. If you're ok with this change, please comment on this issue saying that you relicense your contribution under the LGPL v2.

**Comment by endobson** [comment]
I relicense my contribution under the LGPL v2.

**Comment by soegaard** [comment]
@eu90h ping

**Comment by eu90h** [comment]
I relicense my contributions under the LGPLv2. Apologies for not seeing
this sooner.

**Comment by soegaard** [comment]
@samth Do more people need to be contacted wrt the math library?

**Comment by samth** [comment]
All the people we needed to contact for this issue have agreed.
