### ISSUE TITLE
odd-prime? accepts Natual instead of Integer

### ISSUE THREAD

**Issue by CastixGitHub** [racket/math#17]
The current implementations of `odd-prime?` accepts Natual numbers
https://github.com/racket/math/blob/3a551d09468e7368b2a241eaae5349c883e8d648/math-lib/math/private/number-theory/number-theory.rkt#L128

Meanwhile the documentation says it accepts Integer https://github.com/racket/math/blob/3a551d09468e7368b2a241eaae5349c883e8d648/math-doc/math/scribblings/math-number-theory.scrbl#L310

trying it:
```
> (odd-prime? -7)
. . odd-prime?: contract violation
  expected: Natural
  given: -7
  in: the 1st argument of
      (-> Natural any)
  contract from: 
      <pkgs>/math-lib/math/private/number-theory/number-theory.rkt
  blaming: /home/castix/_/svarione.rkt
   (assuming the contract is correct)
  at: <pkgs>/math-lib/math/private/number-theory/number-theory.rkt:22.9
> (prime? -7)
#t
> 
```
I think the doc should be corrected

**Comment by soegaard** [comment]
The docs were right. I changed the declaration of odd-prime? to be the same as prime?

**Comment by soegaard** [comment]
See https://github.com/racket/math/commit/58f5d6205abeec854b47a6c70d613089f108bceb

**Comment by CastixGitHub** [comment]
Thanks. I'm was worried about backward-compatible code where coders assumed that `odd-prime?` accepted only natural numbers
