### ISSUE TITLE
distribution type docs unclear

### ISSUE THREAD

**Issue by pnwamk** [racket/math#18]
I think perhaps the docs for a `distribution` should be more clear in explaining that it is a polymorphic struct with 2 type parameters (https://docs.racket-lang.org/math/Distribution_Types_and_Operations.html?q=bernoulli-dist#%28def._%28%28lib._math%2Fdistributions..rkt%29._distribution%29%29) since you can write `distribution` as a type and the error messages you get are not at all helpful. (Perhaps the error messages could be improved too...).

E.g., this fails somewhat mysteriously

```
> (ann (poisson-dist) distribution)
  Type Checker: type mismatch
    expected: distribution
    given: Poisson-Dist in: (poisson-dist)
```

and if you're lucky you'll figure out that it works like this (i.e. with the type arguments provided):

```
> (ann (poisson-dist) (distribution Real Real))
- : (distribution Real Real)
(poisson-dist 0.5)
```

**Comment by soegaard** [comment]
@bennn  Did the additions in  #19  also fix this issue?

**Comment by bennn** [comment]
Yes, I made #19 to help with this issue.
