### ISSUE TITLE
Typo in flonum-ployfun.rkt?

### ISSUE THREAD

**Issue by dieggsy** [racket/math#23]
Is `make-polyfun` here: 

https://github.com/racket/math/blob/58f5d6205abeec854b47a6c70d613089f108bceb/math-lib/math/private/flonum/flonum-polyfun.rkt#L36-L41

supposed to be `make-flpolyfun` ? If not, where is `make-polyfun` defined?

**Comment by soegaard** [comment]
I think you are right, that it is supposed to be `make-flpolyfun`.

Will you make a pull request?
