### ISSUE TITLE
Constructing an array object in #lang racket crashes the macro stepper

### ISSUE THREAD

**Issue by Rscho314** [racket/math#24]
As the title suggests, this crashes the macro stepper:

```
#lang racket
(require math/array)
(array #[5])
```

With error:

> Internal error:
> with-syntax1: failed pattern match against
> (?first . ?rest)
> in: ()

But using typed/racket works as expected:

```
#lang typed/racket
(require math/array)
(array #[5])
```

Error dump:
[dump.txt](https://github.com/racket/math/files/3166097/dump.txt)

**Comment by samth** [comment]
This now works as of 7.6.
