### ISSUE TITLE
flonum-tests tests regularly fail

### ISSUE THREAD

**Issue by samth** [racket/math#35]
The tests in flonum-tests.rkt regularly fail (they use randomness). They always seem to find similar bugs in a few `fl` functions. One example is here:

http://drdr.racket-lang.org/53475/cs/racket/share/pkgs/math-test/math/tests/flonum-tests.rkt

For reasons that aren't clear to me, they don't regularly fail on DrDr on the Racket BC build, but the failures exist there too.

It's unclear to me exactly what is being tested, and what is going wrong, but this issue is a place to figure that out.

Relevant to racket/racket-ci#1.

**Comment by samth** [comment]
I still don't know if this is a bug, and if so where, but here's more about what's going on.

#### What the tests are doing

The flonum tests (under a comment suggesting that they are testing the FPU) test the correspondence between Racket's math functions and the functions from `math/bigfloat`. To do this, it calculates the answer both with the math functions (such as `flsin`), and with the bigfloat equivalent (such as `bfsin`), and then checks that they are within the appropriate number of ulps of each other (usually 0.5). 

You can see this failing with the following output (produced by just running the `test-flsin` function.

```
'(((flsin 1.0508668734276366e+308) 1.0))-0.7849352660212705
```

This means that `(flsin 1.0508668734276366e+308)` is 1.0 ulps away from the correct answer, and since 1.0 is bigger than 0.5, that's an error.

#### Precison

Furthermore, it does this calculation with the precision of bigfloats set to 53 (the same as double-precision IEEE floating point). I think this should mean that it always gives exactly the same answer, but this is unclear. 

However, if you do the calculation with larger precision, you can often get different answers. If you use a precision of 500, you get 0.502 ulps (still more than 0.5, though). 

Code for doing all of this, in a manner I find easier to use/read, is here: https://gist.github.com/feda941eaa11d2756f1299590c0d536d

#### Is this a bug?

I had a long Twitter discussion about related issues, you can see it here: https://twitter.com/samth/status/1247256532200325122

In it, Stephen Tyrone suggested that <1 ulp is a good goal. In every case I've found, we hit that. However, we don't always match other language implementations. For example, JS gives a (very slightly) different answer for that sin calculation.

#### What should we do?

I can see a few options:
1. Increase the allowed ulp error to 0.999, and calculate with higher precision. This would probably fix most of the errors, although we'd have to figure out what the allowed error is for a few other things tested (such as the fl2 functions).
2. Change the implementation of these functions to be more accurate. This is probably a lot of work.
3. Remove (some of) these tests.

Unfortunately, the original author of all of these tests, @ntoronto, is no longer active, but maybe he can be persuaded to give some indication of what's intended here. There's also [this paper](https://www.cs.umd.edu/~ntoronto/papers/toronto-2014cise-floating-point.pdf) by him and @jeapostrophe which may shed light on the subject (I haven't looked yet).

#### Other fun

The Racket BC implementation fails about every 5th time just for `flsin` on my machine, but never fails on DrDr, so this was only noticed when Racket CS was added to DrDr. As far as I can tell, these tests have never passed consistently.

cc @mflatt @pmatos

**Comment by jeapostrophe** [comment]
I don't think #3 is the right thing.

I think #2 is likely the best thing, although I don't really know what the constraints are. I feel like it "should" be the case that Racket should just "do whatever C does" or "do whatever the CPU provides" for things like `flsin`, although Neil did put a lot of work into figuring out good implementations for things like `log1p`.

I think that #1 is fine once some effort has gone into #2

**Comment by samth** [comment]
To do (2), we need to choose some level of accuracy to aim for. Possible choices:
1. <1 ulp. I think we basically meet this already, and is what @stephentyrone suggested in that thread.
2. <0.5 ulp This is what the code tests for, and we don't currently meet it. From reading your paper, I don't think we've ever expected that this would be the case, but it's hard to tell.
3. "Whatever C does" Problematically, this is not either a level of accuracy (C doesn't prescribe one), nor is it stable across operating systems or time (I spent a lot of time in that Twitter thread tracking down what turned out to be a change in accuracy in `pow` in glibc). 
4. Correctly rounded. This would be nice but is probably very expensive.

Furthermore, making things more accurate is complicated given the implementation, which basically just calls the C library for `sin`, `exp`, etc, particularly on Racket BC (and I think Racket CS, although I'm less sure how to read the code).

**Comment by samth** [comment]
Further results:

1. When computing the "correct" answer with high precision (128 bits of mantissa), all of the mathematical functions from `racket/flonum` tested here are correct within 1 ulp (or even 0.6 ulp), but many have errors slightly more than 0.5 ulp. 
2. The `math` library also provides a number of other functions which operate on [double-double flonums](https://docs.racket-lang.org/math/flonum.html?q=fl2%2B#%28tech._double._double%29), or return them, such as `fl2+` and `flexp/error`. These functions sometimes have very large error when measured in ulps, for example

```
(flexp/error 247.4773606710883)                         => 3.006437192549783484489163380607e+107                                                                                                                   
(bfexp (bf #e247.477360671088291610431042499840259552)) => 3.006437192549783125869933261781e+107                                                                                                                   
error is 2477676894723501.5 ulps with precision 128   
```

Unfortunately, the docs for these functions say that the highest observed error is 0.5 ulps. 

So far, when testing, the problematic functions are `fl2+`, `fl2exp`, `fl2expm1`, and `flexp/error`, but I don't know whether this suggests anything about the others either way.

To determine these results, I've run the randomized testing with 1000x times more iterations than is usually run (for example, in DrDr).

##### Plan

My suggestions are:

1. We compute the "correct answers" with higher-than-53-bit accuracy, unless @ntoronto tells us a reason to do otherwise.
2. We relax the requirement of ulp error to 0.6.
3. We open a bug report about the larger-than-expected errors for some `math/flonum` functions.
4. We disable random testing in CI for the problematic functions fl2-related, or otherwise modify the tests to not fail with the current implementation.

1 & 2 would fix all problems that I can find in the functions in `racket/flonum`. 3 & 4 seem like the best we can do for the double-double flonum functions in the absence of their author from the project.

**Comment by samth** [comment]
Two additional notes:

1. I plan to open a pull request implementing this plan tomorrow.
2. Running these tests, including every interesting case the random tests have found that I know of, can be done with the code at https://github.com/samth/fltest.
