### ISSUE TITLE
mpfr returns wrong numbers (in DrRacket)

### ISSUE THREAD

**Issue by bdeket** [racket/math#49]
### tested on:
7.8.0.9--2020-08-25(80ad628/a) [3m] - Linux
7.8.0.9--2020-09-02(8ca4977/a) [3m] - Windows

### program run:
```
(require math/bigfloat
         math/base)

(define (random-float)
  (floating-point-bytes->real (integer->integer-bytes (random-bits 64) 8 #f #f) #f))

;; test if two successive calculations with mpfr produce the same result
(define (test bftest args)
  (define zs (build-list args (λ (i) (random-float))))
  (define a (bigfloat->real (apply bftest (map bf zs))))
  (define b (bigfloat->real (apply bftest (map bf zs))))
  (if (equal? a b)
      #f
      (exact->inexact (- b a))))

;; run 20 times 1million tests
(for ([i (in-range 21)])
  (for ([i (in-range 1e6)])
    (define ans (test bf+ 2))
    (when ans
      (printf "mpfr error: ~a\n" ans)))
  (println (list 'done i)))
```

### problem:
In DrRacket, every so often this prints errors (about 1~4 times in a million).
So far I've not been able to reproduce this at the command line.

This is triggered almost instantly if in a seperate DrRacket tab the mpfr library is also used (for example, running the same program). However the first time I noticed it, my file using mpfr was the only one running. But I had been using the mpfr library for a whole day in the same DrRacket instance.

If there is anything I can do to help track this down further, please let me know.

**Comment by pavpanchekha** [comment]
Confirmed on macOS with Racket 7.8.0.7. It seems bad! The importance of concurrency and the rarity makes the naively think memory corruption.

**Comment by mflatt** [comment]
I can replicate the problem, too.

So far, I've found one problem on CS, but that doesn't seem to be the main one (and it's CS specific).

**Comment by mflatt** [comment]
I had never noticed before that `gmp.rkt` has some memory management responsibility. This line looks wrong to me:

https://github.com/racket/math/blob/master/math-lib/math/private/bigfloat/gmp.rkt#L117

The problem is that a finalizer is attached to `z`, but after the `size` and `limbs` fields are extracted, nothing here retains `z`. And in `bigfloat->sig+exp`, nothing otherwise retains `z` while `mpz->integer` is called.

I haven't been able to provoke a crash after changing that to

```
      (begin0
        (size+limbs->integer (mpz-size z) (mpz-limbs z))
        (void/reference-sink z))
```
but I'll check more and look around for other, similar problems.

**Comment by pavpanchekha** [comment]
@mflatt I admit your explanation is beyond me, but thanks for looking. To clarify, I have reproduced it in the BC version.

**Comment by mflatt** [comment]
Yes, the `gpm.rkt` bug affects both BC and CS.

I now see that the CS-specific problem is harmless — a field-reading problem on a field that isn't read — but I'll include an adjustment to that in the PR, anyway.
