### ISSUE TITLE
modexpt - only typed version handles negative exponents

### ISSUE THREAD

**Issue by maueroats** [racket/math#58]
Racket version: 8.0 [cs]

## Problem

```racket
#lang racket
(require math/number-theory)
(with-modulus 11
  (modexpt 2 -1))
```

## Results

Expected result: `6`, the same as `(modular-inverse 2 11)`. 

Actual result:
```
modular-expt: contract violation
  expected: Natural
  given: -1
  argument position: 2nd
  other arguments...:
```
Notice that the error is coming from `modular-expt`.

## Partial Diagnosis

The [modexpt](https://github.com/racket/math/blob/3409a8e6e3b456fd3a5622e525931af49cd456b5/math-lib/math/private/number-theory/modular-arithmetic.rkt#L102) function from the typed-defs submodule in `modular-arithmetic.rkt` contains actual logic to handle negative exponents.

There is another [modexpt](https://github.com/racket/math/blob/3409a8e6e3b456fd3a5622e525931af49cd456b5/math-lib/math/private/number-theory/modular-arithmetic-base.rkt#L73) function in `modular-arithemtic-base.rkt` that does not contain that logic.

The call to `modexpt` is apparently invoking the second one and not the first.

Maybe caused by: the [untyped-defs](https://github.com/racket/math/blob/3409a8e6e3b456fd3a5622e525931af49cd456b5/math-lib/math/private/number-theory/modular-arithmetic.rkt#L144) are the ones providing everything to the top-level (which is then provided to everyone), but it's only the typed version that handles negative exponents?

## Suggested fixes
1. move the code handling negative exponents to [modular-expt](https://github.com/racket/math/blob/3409a8e6e3b456fd3a5622e525931af49cd456b5/math-lib/math/private/number-theory/modular-arithmetic-base.rkt#L73) in the `modular-arithmetic-base` package.
2. someone who knows what they are doing carefully reads the [modular-arithmetic](https://github.com/racket/math/blob/master/math-lib/math/private/number-theory/modular-arithmetic.rkt) file and make sure there are no similar issues 

I can submit a PR for 1 but cannot do 2.

**Comment by soegaard** [comment]
The documentation of modular-expt says n must be positive, so strictly speaking the error message is expected. 
However, I think it would be a nice improvement to support. In the case n negative, consider checking that a and n are coprime, otherwise the modular inverse doesn’t exist. Fix 1 sounds right.

**Comment by maueroats** [comment]
It looks like the inlined modular exponent directly invokes `modular-expt*`. That seems undesirable, but I don't want to change it without checking. I would have thought that all uses should go through the "non-star" version.

I want to find a single place to add handling for negative exponents. They could all go in `modular-expt*`, but I thought that function was there for efficient calculation only. (Although it looks like it has not called itself recursively in recent memory, so maybe it should all just be in `modular-expt`?)

Touching old stuff is dangerous. Do you have a preference?

**Comment by maueroats** [comment]
Actually, let me guess: the `*` version is for the inliner, which wants to put the modulus first. Normal humans want the modulus last. The change should actually go in the `*` version.
