### ISSUE TITLE
Problem with libmpfr-4.dll on windows

### ISSUE THREAD

**Issue by bdeket** [racket/math#77]
On windows, the currently bundled dll for mpfr is broken in some way.
I tested the dll from the current snapshot 8.7.0.5--2022-11-03(0e0564a/a) and release 8.6. which both don't work.
The dll bundled with 8.5 does work. (I mean: dropping in the libmpfr-4.dll from racket 8.5 in the current snapshot lib directory solves the problem)

Further: the error is quite obscure, all bigfloat related operations just report:
```
mpfr_set_nan: implementation not found
  arguments...:
   #<_mpfr>
```

**Comment by soegaard** [comment]
@jbclements Any ideas?

**Comment by mflatt** [comment]
I'm surprised that this wasn't noticed before, but I can replicate the problem. It's almost certainly an issue with the libmpfr-4 build as upgraded in v8.6.

**Comment by mflatt** [comment]
I've pushed an update to the "math-win32-x86_64" and "math-win32-i386" packages. I'm not sure whether they'll be in v8.7, but the release managers will discuss.
