### ISSUE TITLE
Cardinality of matrix procedures, versus documentation

### ISSUE THREAD

**Issue by kengruven** [racket/math#86]
The documentation for `matrix+` is:

```
@deftogether[(@defproc[(matrix+ [M (Matrix Number)] [N (Matrix Number)] ...) (Matrix Number)]
```

This suggests that it requires at least 2 args, but (like `+` which is `@defproc[(+ [z number?] ...) number?]`) it actually works fine with just 1.

The same goes for `matrix-` and `matrix*`.

`matrix=` is even stranger.  Its documentation is:

```
@defproc[(matrix= [M0 (Matrix Number)] [M1 (Matrix Number)] [N (Matrix Number)] ...) Boolean]
```

which suggests it requires at least *3* args, when it only requires 2.

(Is that an implementation mistake, too?  Plain `=` can be called with just 1, and I see no reason `matrix=` couldn't work with 1 arg, as well.)

**Comment by sorawee** [comment]
`...` in Racket means zero or more (see https://docs.racket-lang.org/reference/notation.html). Therefore, `(matrix+ [M (Matrix Number)] [N (Matrix Number)] ...)` accepts at least one or more arguments.

**Comment by sorawee** [comment]
As for `matrix=`, yeah, that's inconsistent with `=`, but I wouldn't say it's wrong per se.

There's also an argument to make `=` work with 0 arguments, and `matrix=` probably should follow that too.

**Comment by kengruven** [comment]
> `...` in Racket means zero or more (see https://docs.racket-lang.org/reference/notation.html). Therefore, `(matrix+ [M (Matrix Number)] [N (Matrix Number)] ...)` accepts one or more arguments.

Yes, `...` means "zero or more", so `M N ...` is two or more: M is one, then N is two, then zero or more after that ... right?  Maybe I'm missing something.

**Comment by rfindler** [comment]
> > `...` in Racket means zero or more (see https://docs.racket-lang.org/reference/notation.html). Therefore, `(matrix+ [M (Matrix Number)] [N (Matrix Number)] ...)` accepts one or more arguments.
> 
> Yes, `...` means "zero or more", so `M N ...` is two or more: M is one, then N is two, then zero or more after that ... right? Maybe I'm missing something.

The way to think about the ellipsis is as a post-fix operator -- it doesn't stand alone, it modifies the thing before it. So this means that "M N ..." is a short hand for someone to make a choice. They can choose "M" or "M N" or "M N N" or "M N N N", etc. The main value of this is that you don't have ambiguity about what the ellipsis is actually going to be filled up with. It allows you to only fill it up with precisely whatever "N" is.

**Comment by kengruven** [comment]
Oh, right.  I'm an idiot.  (I was comparing to `+` but that operator has an identity so it allows a no-arg form.)  Sorry.

I still think `matrix=` should allow 1 arg, analogous to `=`, but I don't actually have a use for that.  And I see `array=` means something completely different, as well, so maybe I shouldn't be too concerned about consistency here.
