### ISSUE TITLE
Fix build-array calling proc n*m+1 times

### ISSUE THREAD

**Issue by maximvl** [racket/math#9]
Hi! I recently found that `build-array` calls it's last argument one more extra time for determining the type of the elements.

There is an extra call here: https://github.com/racket/math/blob/master/math-lib/math/private/array/for-each.rkt#L142-L143 , `(make-vector size (g js0 0))`.
So it isn't efficient, but also makes it hard to put side effects into `proc`.
Proposed solution is to save that first, `(g js 0)` element, and use for both making vector and constructing matrix.

**Comment by stamourv** [comment]
Sounds like a good idea!
Want to give it a shot? Looks like you've already found the relevant code.
If you have any questions, just let me know!

**Comment by spdegabrielle** [comment]
is this still an issue?
